// Code generated by k8s code-generator DO NOT EDIT.

/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/iSofiane/flink-on-k8s-operator/pkg/apis/flinkoperator.k8s.io/v1alpha1"
	scheme "github.com/iSofiane/flink-on-k8s-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FlinkApplicationsGetter has a method to return a FlinkApplicationInterface.
// A group's client should implement this interface.
type FlinkApplicationsGetter interface {
	FlinkApplications(namespace string) FlinkApplicationInterface
}

// FlinkApplicationInterface has methods to work with FlinkApplication resources.
type FlinkApplicationInterface interface {
	Create(*v1alpha1.FlinkApplication) (*v1alpha1.FlinkApplication, error)
	Update(*v1alpha1.FlinkApplication) (*v1alpha1.FlinkApplication, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.FlinkApplication, error)
	List(opts v1.ListOptions) (*v1alpha1.FlinkApplicationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FlinkApplication, err error)
	FlinkApplicationExpansion
}

// flinkApplications implements FlinkApplicationInterface
type flinkApplications struct {
	client rest.Interface
	ns     string
}

// newFlinkApplications returns a FlinkApplications
func newFlinkApplications(c *FlinkoperatorV1alpha1Client, namespace string) *flinkApplications {
	return &flinkApplications{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the flinkApplication, and returns the corresponding flinkApplication object, and an error if there is any.
func (c *flinkApplications) Get(name string, options v1.GetOptions) (result *v1alpha1.FlinkApplication, err error) {
	result = &v1alpha1.FlinkApplication{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("flinkapplications").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FlinkApplications that match those selectors.
func (c *flinkApplications) List(opts v1.ListOptions) (result *v1alpha1.FlinkApplicationList, err error) {
	result = &v1alpha1.FlinkApplicationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("flinkapplications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested flinkApplications.
func (c *flinkApplications) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("flinkapplications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a flinkApplication and creates it.  Returns the server's representation of the flinkApplication, and an error, if there is any.
func (c *flinkApplications) Create(flinkApplication *v1alpha1.FlinkApplication) (result *v1alpha1.FlinkApplication, err error) {
	result = &v1alpha1.FlinkApplication{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("flinkapplications").
		Body(flinkApplication).
		Do().
		Into(result)
	return
}

// Update takes the representation of a flinkApplication and updates it. Returns the server's representation of the flinkApplication, and an error, if there is any.
func (c *flinkApplications) Update(flinkApplication *v1alpha1.FlinkApplication) (result *v1alpha1.FlinkApplication, err error) {
	result = &v1alpha1.FlinkApplication{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("flinkapplications").
		Name(flinkApplication.Name).
		Body(flinkApplication).
		Do().
		Into(result)
	return
}

// Delete takes name of the flinkApplication and deletes it. Returns an error if one occurs.
func (c *flinkApplications) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("flinkapplications").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *flinkApplications) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("flinkapplications").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched flinkApplication.
func (c *flinkApplications) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FlinkApplication, err error) {
	result = &v1alpha1.FlinkApplication{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("flinkapplications").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
