apiVersion: "flinkoperator.k8s.io/v1alpha1"
kind: FlinkApplication
metadata:
  name: flink-test
  namespace: default
spec:
  image: "flinkk-latest"
  jobmanager:
    serviceAccount: flink
  taskmanager:
    instances: 1
