// +build !ignore_autogenerated

// Code generated by k8s code-generator DO NOT EDIT.

/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlinkApplication) DeepCopyInto(out *FlinkApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlinkApplication.
func (in *FlinkApplication) DeepCopy() *FlinkApplication {
	if in == nil {
		return nil
	}
	out := new(FlinkApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlinkApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlinkApplicationList) DeepCopyInto(out *FlinkApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FlinkApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlinkApplicationList.
func (in *FlinkApplicationList) DeepCopy() *FlinkApplicationList {
	if in == nil {
		return nil
	}
	out := new(FlinkApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlinkApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlinkApplicationSpec) DeepCopyInto(out *FlinkApplicationSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	in.Jobmanager.DeepCopyInto(&out.Jobmanager)
	in.Taskmanager.DeepCopyInto(&out.Taskmanager)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlinkApplicationSpec.
func (in *FlinkApplicationSpec) DeepCopy() *FlinkApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(FlinkApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlinkApplicationStatus) DeepCopyInto(out *FlinkApplicationStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlinkApplicationStatus.
func (in *FlinkApplicationStatus) DeepCopy() *FlinkApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(FlinkApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobmanagerSpec) DeepCopyInto(out *JobmanagerSpec) {
	*out = *in
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.JavaOptions != nil {
		in, out := &in.JavaOptions, &out.JavaOptions
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobmanagerSpec.
func (in *JobmanagerSpec) DeepCopy() *JobmanagerSpec {
	if in == nil {
		return nil
	}
	out := new(JobmanagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskmanagerSpec) DeepCopyInto(out *TaskmanagerSpec) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskmanagerSpec.
func (in *TaskmanagerSpec) DeepCopy() *TaskmanagerSpec {
	if in == nil {
		return nil
	}
	out := new(TaskmanagerSpec)
	in.DeepCopyInto(out)
	return out
}
